#+TITLE: Surviving Lawlessness - Chapter 1, Section 1-2
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allegreya">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

* Introduction
Like it or not, things are happening all the time. Even worse, you don't know when a lot of these things will happen. Sure, you might have a general idea - kids learn to walk around the age of 1 or so, students tend to graduate after 4 years of undergraduate school, and dogs learn to shake after a certain number of treats and head scratches. But you don't know EXACTLY when these things happen. But if you're clever, you can work up a handful of tools to help predict when something might happen. You've given your dog 20 treats and head pats - what is the probability that he's finally going to nail the handshake thing on the next one? Or maybe you provide a group of students with a dedicated tutor - do they graduate faster? These are the kinds of questions you can answer if you are willing to wade into the mires of statistics. Don't worry. We're going to do this together. I even brought you a snorkel.

* Definitions
You - like me - are only learning about this so you can impress all your friends at dinner parties. You go to many of these parties because you are very popular and normal. But in order to woo your friends, you need to know what to call these things.

All the above mentioned scenarios - dog shaking, baby walking, student graduating - they're 'events'. And they take a certain amount of 'time' to happen. So the analysis of them is called 'time to event analysis'. Easy enough. Sometimes it's called 'survival analysis', because it's used a lot when applied to people - sometimes it's useful to see if a drug is keeping people alive, but unfortunately the alternative is death. You want to track how long they /survive/ (Aside: yes, there are other ways to study people besides just alive/dead. But give me a break. I'm trying to write some notes here.)

We'll learn the complications of this analysis as we move along.

* Teaching cats to sing
A book about time-to-event analysis might get a little hung up on things that break, die, or wear out. But that's a little depressing. So when possible, I'm going to talk about other subjects. Particularly cats. Plus, thinking about how this applies to, say, human survival is a good mental exercise.

Let's imagine that all cats can sing. You haven't heard many cats sing because no one has bothered to try to train them. But with enough training, /ALL/ cats can sing. Note - no cats are BORN able to sing. They need training. (I'm setting up these rules because they are involved in math later. Don't worry about it now.)

You've been training your cat since it was born, and it's been a couple months now: no singing. Should you be worried?

** The probability density function
You poke around the neighborhood and see how your neighbors are faring teaching their cats to sing. They've all been training their cats since birth (the cat's birth, not theirs) and told you the age that the cat started singing. You make a little plot:

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file five_cats.svg
library(ggplot2)
library(bladdr)

set.seed(1)
n <- 5
df <- data.frame(
  cat = 1:n,
  sing_time = rgamma(n, 2)
)
ggplot(df, aes(x = sing_time, y = cat)) +
  geom_segment(aes(x = 0, y = cat, xend = sing_time, yend = cat)) +
  geom_point() +
  theme_tufte(20) +
  labs(x = "Cat age (human years)",
       y = "Cat") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:five_cats.svg]]

Looks like most cats are taking more than a year or two to learn how to sing. Your fears are put at ease for a moment, but you're not an idiot: you know just a few samples can be misleading. Plus you know this information will NOT be motivating for your cat. You begin a cat census, asking everyone who has started training their cat from birth how long it took them for their cats to sing. The best you can do is scrape together 100 people (this is not a popular hobby):

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file 100_cats.svg
library(ggplot2)
library(bladdr)

set.seed(2)
n <- 100
df <- data.frame(
  cat = 1:n,
  sing_time = sort(rgamma(n, 2))
)
ggplot(df, aes(x = sing_time, y = cat)) +
  geom_segment(aes(x = 0, y = cat, xend = sing_time, yend = cat)) +
  theme_tufte(20) +
  labs(x = "Cat age (human years)",
       y = "Cat") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:100_cats.svg]]

It looks like somewhere between 1-2 years is the sweet spot for when most cats get their voice. You think about plotting these results a different way - a density histogram.

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file 100_cats_dense.svg
df |> ggplot(aes(x = sing_time)) +
  geom_density() +
  theme_tufte() +
  labs(x = "Cat age (human years)") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())

#+end_src

#+RESULTS:
[[file:100_cats_dense.svg]]

It looks a bit lumpy. You want to know if there truly is a 'second wind' of learning at around 5 years or if it's just statistical noise - but you really left it all out on the field when you made all those calls for the cat census. You don't think you could gather even /more/ cat data.

Whenever you are faced with these issues, you know just where to go: the lady with completely black eyes that lives in the woods in a dilapidated cottage. She give you (in exchange for a surprisingly large amount of viscera from forest fauna) a beautiful plot (which as we all know is - by itself - worth all the viscera in the world). But this is not any plot: it is the fabled plot you seek, the one that shows the theoretical distribution of time-to-cat-singing. It's what you would have gotten if you had done an infinite cat census:

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file many_cats_dense.svg
library(ggplot2)
library(bladdr)

ggplot(data.frame(x = c(0, 11)), aes(x)) +
  stat_function(fun = dgamma, args = c(2)) +
  theme_tufte() +
  labs(x = "Cat age (human years)") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:many_cats_dense.svg]]


You notice that the highest peak is at around 1 year of age. This is around the time where most cats will learn to sing, but it looks like it's possible for cats so sing earlier and later, too. (Note that I mentioned earlier that ALL cats will learn how to sing.)

This plot is the visual representation of a /probability density function/, or (somewhat confusingly for fans of the widely used Adobe file format) a pdf. To explain why it's called that, a trick question: What is the probability that a cat will learn to sing on the instant of its 2nd birthday? Answer: 0. Why? Because that instant is such a very very very very (etc) short amount of time. I don't care that the plot shows a high peak at that point - if we're betting on when your cat would sing, and you say 'the instant it turns 1', I'm betting everything I got against you.

Density can also refer to materials. A quick search tells me that osmium is the densest naturally occurring material on Earth (besides me, depending on who you ask). Its density is 22.59g/cm³. So, tell me: how heavy is it in the smallest possible unit of volume? I'm not even talking mm, or nm - not even angstroms. I'm talking about an infinitesimally small point in space. You know the answer. It's 0g.

The probability density relates to our physical density in that physical density measures mass over volume, /this/ (but not all) probability density measures events over time.

** Doing stuff with the pdf
Water has a convenient density of around 1g/mL. Knowing this, and knowing someone has 10mL of water, you can tell them that they have 10g of water. They don't care. But you can do it.

Just like you can find out how much mass of a substance there is by knowing how much volume there is and knowing its density, you can also figure out the probability of an event happening by knowing the pdf and the time range.

Before we go any further, some math notation. I'm going to call the pdf $f$, and some arbitrary time $t$. So $f(t)$ is the probability of some event at time $t$ (which is, remember, 0).

This function isn't as useless as it seems. If we multiply the pdf by time, we should get the probability of an event happening over that range of time. Except...our probability varies over time. With physical density, it didn't vary across the volume of the object (provided it's a pure substance), so we could just multiply two constant numbers (the volume times the density) together and call it a day. We could do that if cats learned to sing with a constant probability over time, but they don't: as we saw, there's a higher probability at age 1, and lower everywhere else. The probability of a cat learning to sing from age 4 to 6 is much lower than from age 1 to 3.

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file many_cats_highlight.svg
library(ggplot2)
library(bladdr)

ggplot(data.frame(x = c(0, 11)), aes(x)) +
  stat_function(fun = dgamma, args = c(2)) +
  stat_function(fun = dgamma, args = c(2), xlim = c(1, 3), geom = "area", fill = "green") +
  stat_function(fun = dgamma, args = c(2), xlim = c(4, 6), geom = "area", fill = "red") +
  theme_tufte() +
  labs(x = "Cat age (human years)") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:many_cats_highlight.svg]]


It's almost like...it matters...how much area is under the curve

*** Uh oh
Yeah. I know. Calculus. Integrals, to be specific. Unfortunately, they're very good at finding the area under the curve in a very general way.

*** Integrating the pdf
One useful function to have to know what the probability that Fluffy should have learned to sing by now - that is, the integral from birth ($t = 0$) to now ($t$).

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file many_cats_0-to-t.svg
library(ggplot2)
library(bladdr)

ggplot(data.frame(x = c(0, 11)), aes(x)) +
  stat_function(fun = dgamma, args = c(2)) +
  stat_function(fun = dgamma, args = c(2), xlim = c(0, 2), geom = "area", fill = "gray50") +
  theme_tufte() +
  labs(x = "Cat age (human years)") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:many_cats_0-to-t.svg]]

$$
F(t)=Pr(T≤t)=\int_{0}^{t}f(x)dx
$$

We call that function $F(t)$. In the medical field, you might consider this function the probability that a patient will have died between, say, when they were diagnosed ($t = 0$) and now ($t$).

Another useful function is one that tells you the probability of Fluffy still not being able to sing at some time ($t$). This is the integral from $t$ to $∞$.

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file many_cats_t-to-inf.svg
library(ggplot2)
library(bladdr)

ggplot(data.frame(x = c(0, 11)), aes(x)) +
  stat_function(fun = dgamma, args = c(2)) +
  stat_function(fun = dgamma, args = c(2), xlim = c(2, 11), geom = "area", fill = "gray50") +
  theme_tufte() +
  labs(x = "Cat age (human years)") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:many_cats_t-to-inf.svg]]

$$
S(t)=Pr(T≥t)=\int^{∞}_{t}f(x)dx
$$

In the medical field, this might be the probability that a patient will survive until time $t$. This is why it's called the 'survival function' and is denoted by $S$.

$S(t)$ has some important properties. It always goes down, never up - also known as 'monotone decreasing'. It also starts at 1 (that is, $S(0) = 1$. And it ends at 0 ($S(∞) = 0$). Thus, no cats are born singing, and all cats can learn to sing.

Side note - $S(t)$ HAS to be monotone decreasing because it is the integral of a function that can never be negative (you'll need to think about the relationship between a curve and its integral - but basically it goes up whenever it 'adds' more area under the curve and goes down whenever it 'subtracts' area under the curve - which happens when the curve being integrated goes below 0). $f(t)$ can never be negative, because negative probabilities do not make sense. It either happens or it doesn't - it can't 'anti-happen'.

So, $F(t)$ is the probability that an event will have occurred by time $t$, while $S(t)$ is the probability that an event will NOT have occurred by time $T$.

It's important to note that if your patient had a 90% chance of not making it to time $t$ (that is, $F(t) = 0.9$), yet they are still alive, it does not mean that your patient has only a 10% chance of dying in the future! That would be bonkers. You roll the dice on that patient and they have a 9/10 chance of immortality? No. What this means is that in all the patients seen previously, 90% of them didn't make it this long, and 10% of them made it longer. Unfortunately, in the end, death still comes for us all. We'll learn how to properly calculate their probability of dying in the future in the next section.

** Hazard rates
So, a cat has trained for 7 years and sits in front of you, utterly mute. Suppose we naively tried to use our pdf to determine the probability of this cat learning to sing some time in the future:

#+HEADER: :R-dev-args bg="transparent" :width 7 :height 3.5
#+begin_src R :results graphics file :session :exports results :file 7-to-17.svg
library(ggplot2)
library(bladdr)

ggplot(data.frame(x = c(0, 11)), aes(x)) +
  stat_function(fun = dgamma, args = c(2)) +
  stat_function(fun = dgamma, args = c(2), xlim = c(2, 11), geom = "area", fill = "gray50") +
  theme_tufte() +
  labs(x = "Cat age (human years)") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())
#+end_src

#+RESULTS:
[[file:7-to-17.svg]]

We calculate the area under the curve to be...0.0073. Or 0.7%. Are we doomed to have a cat that can't sing???

No, because we assume that all cats will EVENTUALLY learn to sing. But how do we take this in to account? We have to take into account all the time that the cat HASN'T learned how to sing. Another way to say this is that it needs to be /conditional/ on the fact that the cat has existed this long without learning to sing.

What we really want to know is some measure of the imminence of an event.

This exists, and is known as the 'hazard rate'. If velocity measures how soon you're going to hit your next meter, then hazard rate measures how soon you're going to hit your next event.

Let's put the question we're actually asking into words:

Given that our cat has not yet sung at age 7, what is the probability that this cat will learn to sing in the next...10/5/1 year(s)?

Or rather:

$$Pr(t≤T < t + Δt|T≥t)$$

The bar ($|$) means 'given'. So, assuming that our cat has gone this long without singing ($| T≤t$) what is $Pr(t≤T < t + Δt)$ (the probability that it'll learn how to sing in this next time frame ($Δt$))?

This is what we WANT. How we get it requires a little rearranging - but we /can/ do it. To pull this off, we need to know Bayes theorem. This guy is super hot right now as well as super dead, but we don't need to go in to that. What we need to know is that he proved this:

$$
Pr(A|B) = \frac{Pr(B|A)Pr(A)}{Pr(B)}
$$

If we compare it to our previous equation, we can match it up by setting $A = t≤T < t + Δt$ and $B = T≥t$. Substituting in our own $A$ and $B$, we get:

$$
Pr(t≤T < t + Δt|T≥t) = \frac{Pr(T≥t|t≤T < t + Δt)Pr(t≤T < t + Δt)}{Pr(T≥t)}
$$

We can work with this. Let's go through the chunks one at a time:

$$
Pr(T≥t|t≤T < t + Δt)
$$

Reading this out: What is the probability that our cat has learned to sing either now or in the future, given that our cat has learned to sing now or a little bit in the future?

You might be able to sense the repetition here. What's the probability of something happening given it's happened? Well...it's guaranteed. It happened. 100%. 1.

$$
Pr(T≥t|t≤T < t + Δt) = 1
$$

Next chunk:

$$
Pr(t≤T < t + Δt)
$$

This is the probability that your cat will sing between now and a bit in the future. We know this too - it's from the pdf. It's just a tiny integral:

$$
Pr(t≤T < t + Δt) = ∫_{t}^{t + Δt}f(x)dx
$$

And finally:

$$
Pr(T≥t)
$$

We've seen this before, exactly - It's $S(t)$

$$
Pr(T≥t) = S(t)
$$

All together:

$$
Pr(t≤T < t + Δt|T≥t) = \frac{1×∫_{t}^{t + Δt}f(x)dx}{S(t)}
$$

This is the probability of experiencing some event in a given time frame, given no event has been observed previously. This last 'conditional' part is important, since a dead guy has no chance of dying in the future.

It can be mathematically useful to determine the 'instantaneous rate' of an event. This is the hazard rate, or hazard function. The interpretation of this is quite challenging, and in my personal opinion it tends to be more useful when used /for/ other things, rather than as itself.

It's just the probability we calculated above, divided by the same time frame ($Δt$), as the time frame approaches 0. A higher value means greater imminence of the event, a smaller number means lower imminence. It can go up and down, but it can't be negative. It can be way, way bigger than 1, so it's not a probability.

$$
h(x) = \lim_{Δt → 0} \frac{∫_{t}^{t + Δt}f(x)dx}{S(t)} = \frac{f(x)}{S(t)}
$$

Often, hazard functions go up over time - like in our cat example, and also in human mortality. But they don't always need to go up. Sometimes the longer you've been around, the longer you WILL be around (known as the 'Lindy effect'). But the cumulative hazard DOES need to go up. So while it might be less risky to at each moment to keep on going, the amount of risk you experience is still non-zero, and it does get added to the ledger of risk you've experienced all time. It's like the risk of making a mistake when learning to play the piano. If you've miraculously managed to never make a mistake during the beginning stages, the risk of you making a mistake as you get better goes down. But over a long enough time, you still risk making a mistake, even if you are quite good.

I'm not super jazzed about a practical interpretation of hazard functions, but here I go:

This hazard function represents the expected number of events for a given time period, assuming that the event hasn't already happened. We could interpret $h(10) = 100$ to mean that we would expect a 10 year old cat that hasn't learned to sing 100 times over during the next unit of time (in this case, years). That is, if our cat learned to sing, and then had the memory deleted from its memory, it could learn, then forget, then learn, then forget..100 times over during the course of a year.
