* Introduction
Like it or not, things are happening all the time. And even worse, you don't know when a lot of these things will happen. Sure, you might have a general idea - kids learn to walk around the age of 1 or so, students tend to graduate after 4 years of undergraduate school, and dogs learn to shake after a certain number of treats and head scratches. But you don't know EXACTLY when these things happen. But if you're clever, you can work up a handful of tools to help predict when something might happen. You've given your dog 20 treats and head pats - what is the probability that he's finally going to nail the handshake thing on the next one? Or maybe you provide a group of students with a dedicated tutor - do they graduate faster? These are the kinds of questions you can answer if you are willing to wade into the mires of statistics. Don't worry. We're going to do this together. I even brought you a snorkel.

* Definitions
You - like me - are only learning about this so you can impress all your friends at dinner parties. You go to many of these parties because you are very popular and normal. But in order to woo your friends, you need to know what to call these things.

All the above mentioned scenarios - dog shaking, baby walking, student graduating - they're 'events'. And they take a certain amount of 'time' to happen. So the analysis of them is called 'time to event analysis'. Easy enough. Sometimes it's called 'survival analysis', because it's used a lot when applied to people - sometimes it's useful to see if a drug is keeping people alive, but unfortunately the alternative is death. You want to track how long they /survive/ (Aside: yes, there are other ways to study people besides just alive/dead. But give me a break. I'm trying to write some notes here.)

All of these things happen (are 'events', as we might call them) and happen at a certain 'time'. They might be best analyzed by /time to event/ analysis.

We'll learn the complications of this analysis as we move along.

* Teaching cats to sing
My initial feeling of writing this was


It would be nice to predict when some things would happen. Turns out, that's a bit more involved than you might expect.

Let's get started.

Suppose you already know the probability when a baby will take its first steps at any given moment. A lady with completely black eyes demanded the head of an elk and in return you were given a beautiful plot (which in itself is worth an elk head). But this plot shows the probability of a child learning to walk at every instant in his life.

You gaze upon it and see the graph is quite low at the beginning. Babies fresh from the womb are more concerned with crying (understandable) than walking. As they grow up they tend to be a little more keen on walking at around a year old, so you see the plot go up. But then you see something strange. After about 2 years, the plot dips down again. Wait, you might think - shouldn't it get more likely for a baby - now toddler - to take their first steps the older they get? But this makes sense: if a child hasn't taken their first steps by age 2, it's possible something is preventing them - like lacking functional legs, or legs at all. Or perhaps they live in a house that has a floor that is just trampolines, and that's a little bit hard to get the hang of for your first steps. For these babies, it would take a while for them to get the hang of it (perhaps the babies without functional legs would get very cool mecha-legs). What's important to note is that in this plot, we assume that all babies EVENTUALLY will walk. This is not always the case.

This beautiful plot you were given by the demon lady is known as a probability density function.

* Questions
- Does an event have to have a possibility of not happening? Or could we do survival analysis on something that does not have the possibility of happening, like biological males getting pregnant?
  - By definition, a probability density function must integrate to 1
